# Generated by Django 5.2.5 on 2025-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangelogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_id", models.CharField()),
                ("lifecycle_status", models.CharField()),
                ("object_id", models.CharField()),
                ("label", models.CharField()),
                ("commit_hash", models.CharField()),
                ("committed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    (
                        "dataset_id",
                        "lifecycle_status",
                        "object_id",
                        "label",
                        "commit_hash",
                        "committed_at",
                    )
                },
            },
        ),
    ]
