# Generated by Django 5.2.9 on 2026-01-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangelogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_id", models.CharField()),
                ("status", models.CharField()),
                ("object_id", models.CharField()),
                ("label", models.CharField()),
                ("commit_hash", models.CharField()),
                ("committed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    ("dataset_id", "status", "object_id", "label", "commit_hash", "committed_at")
                },
            },
        ),
    ]
